import { Project, Partner, EquipmentItem, PersonnelItem } from '../types';

export const TRAN_GIA_INFO = {
  companyName: 'CÔNG TY TNHH DỊCH VỤ THƯƠNG MẠI VÀ XÂY DỰNG TRẦN GIA',
  brandName: 'TRẦN GIA PROFILE & CONSTRUCTION',
  shortName: 'TRẦN GIA',
  director: 'TRẦN XUÂN ANH',
  address: 'Xóm Chùa, Thôn Trung Cao, Xã Phú Nghĩa, Thành phố Hà Nội',
  phone: '0986 078 270',
  hotline: '0986 078 270',
  email: 'trangia.kt69@gmail.com',
  website: 'https://trangiaconstruction.vn',
  slogan: 'Uy tín - Chất lượng - Chính xác',
  yearEstablished: '2020',
  totalStaff: '50+ Cán bộ - CNV & Kỹ sư',
  skilledWorkers: '36 công nhân kỹ thuật tại xưởng & công trình',
  seasonalWorkers: '50 - 200 lao động thời vụ',
  pdfFileName: 'HSNL TRANGIA.pdf',
};

export const CEO_LETTER = {
  title: 'THƯ NGỎ TỪ BAN GIÁM ĐỐC',
  author: 'TRẦN XUÂN ANH',
  position: 'Giám đốc Công ty TNHH Dịch vụ Thương mại và Xây dựng Trần Gia',
  salutation: 'Kính gửi Quý Chủ đầu tư, Quý Khách hàng và Quý Đối tác!',
  paragraphs: [
    'Lời đầu tiên, chúng tôi xin gửi lời cảm ơn chân thành đến tất cả Quý khách hàng đã tin tưởng, ủng hộ và sử dụng các sản phẩm, dịch vụ của Trần Gia trong suốt thời gian qua.',
    'Với định hướng phát triển bền vững, Công ty TNHH Thương Mại Dịch Vụ và Xây Dựng Trần Gia đã từng bước đi lên và khẳng định mình là một đơn vị hàng đầu trong lĩnh vực thiết kế thi công nội thất, trần, vách, sơn bả hoàn thiện và thi công hoàn thiện xây dựng... Trong suốt quá trình phát triển của mình, Trần Gia luôn không ngừng phấn đấu, nghiên cứu, cải tiến chất lượng các sản phẩm và dịch vụ nhằm phục vụ tốt nhất các yêu cầu ngày càng cao của Quý Khách hàng.',
    'Với phương châm "Uy tín - Chất lượng - Chính xác", Trần Gia luôn tôn trọng và hết lòng phục vụ tất cả các khách hàng. Sự tin tưởng, ủng hộ của Quý khách hàng sẽ là động lực thôi thúc đẩy Trần Gia ngày càng cố gắng hơn nữa, phấn đấu hơn nữa để đem lại lợi ích cao nhất cho Quý khách hàng. Trần Gia sẽ luôn đồng hành cùng với sự thành công của Quý khách hàng trong một tương lai phát triển bền vững.',
    'Để thực hiện công cuộc hiện đại hóa, theo sự phát triển của xã hội nói chung và ngành xây dựng nói riêng, chúng tôi luôn tìm kiếm nguồn năng lực trẻ, năng động sáng tạo, được đào tạo bài bản, tạo nên sự khác biệt, tiện nghi bậc nhất trong không gian xây dựng của Quý Khách hàng.',
    'Một lần nữa, chúng tôi xin gửi lời cảm ơn chân thành nhất, lời chúc thành công nhất đến tất cả Quý khách hàng đã tin tưởng và đồng hành cùng Trần Gia!',
  ],
  sloganHighlight: 'Uy tín - Chất lượng - Chính xác',
};

export const VISION_MISSION_VALUES = {
  vision: {
    title: 'TẦM NHÌN PHÁT TRIỂN',
    content:
      'Bằng nỗ lực lao động và sáng tạo cùng sự áp dụng khoa học quản lý, Công Ty TNHH Thương Mại Dịch Vụ và Xây Dựng Trần Gia mong muốn trở thành một đơn vị hàng đầu trong lĩnh vực thiết kế thi công nội thất, trần, vách, sơn bả hoàn thiện và thi công hoàn thiện xây dựng trên phạm vi toàn quốc.',
  },
  mission: {
    title: 'SỨ MỆNH',
    content:
      'Cung cấp một hệ thống dịch vụ đồng bộ, khép kín với chất lượng và phong cách phục vụ chuyên nghiệp nhất, đáp ứng cho khách hàng những công trình như ý. Trần Gia luôn cam kết mọi khách hàng của chúng tôi sẽ luôn được sử dụng những sản phẩm tốt nhất, đẹp nhất, chất lượng nhất.',
  },
  coreValues: [
    {
      title: 'Uy tín',
      desc: 'Giữ vững niềm tin bằng tinh thần trách nhiệm cao nhất và sự minh bạch trong mọi cam kết.',
      icon: 'ShieldCheck',
      color: '#0284C7',
    },
    {
      title: 'Tiến độ',
      desc: 'Cam kết bàn giao đúng thời gian, tối ưu hóa quy trình để đảm bảo hiệu quả công việc vượt trội.',
      icon: 'Clock',
      color: '#EA580C',
    },
    {
      title: 'Chất lượng',
      desc: 'Tỉ mỉ, chuẩn xác trong từng chi tiết thi công, kiến tạo những giá trị bền vững theo thời gian.',
      icon: 'Award',
      color: '#16A34A',
    },
    {
      title: 'Sáng tạo',
      desc: 'Đổi mới không ngừng, ứng dụng kỹ thuật và vật liệu mới nhằm mang đến giải pháp khác biệt.',
      icon: 'Lightbulb',
      color: '#F59E0B',
    },
    {
      title: 'Chuyên nghiệp',
      desc: 'Làm việc tận tâm, quy trình làm việc chuẩn chỉ, kiểm soát chất lượng nghiêm ngặt từ xưởng đến công trường.',
      icon: 'Briefcase',
      color: '#6366F1',
    },
    {
      title: 'Nỗ lực',
      desc: 'Luôn phấn đấu hết mình để vượt qua thách thức và đạt kết quả tốt nhất cho khách hàng.',
      icon: 'Flame',
      color: '#E11D48',
    },
  ],
};

export const OPERATING_PRINCIPLES = [
  {
    target: 'VỚI KHÁCH HÀNG',
    icon: 'Users',
    bullets: [
      'Chất lượng, uy tín, tiến độ luôn là ưu tiên số 1.',
      'Luôn thỏa mãn các nhu cầu của tất cả khách hàng với chất lượng tốt nhất.',
      'Cởi mở, thân thiện, cầu thị, nhiệt tình và trân trọng khách hàng.',
      'Nỗ lực cao nhất để các dịch vụ luôn tiến bộ hơn, góp phần nâng cao giá trị kinh tế cho khách hàng.',
    ],
  },
  {
    target: 'VỚI NHÂN VIÊN',
    icon: 'UserCheck',
    bullets: [
      'Tạo cơ hội học tập, nâng cao trình độ chuyên môn và tác phong làm việc chuẩn quốc tế.',
      'Tạo cơ hội thăng tiến trên cơ sở hiệu quả công việc, tính chính trực và sự cống hiến.',
      'Đảm bảo môi trường làm việc an toàn, thu nhập thỏa đáng và sự phát triển bền vững của mỗi cá nhân.',
    ],
  },
  {
    target: 'VỚI ĐỐI TÁC',
    icon: 'Handshake',
    bullets: [
      'Xây dựng và giữ gìn mối quan hệ đoàn kết, ổn định, lâu dài và cùng có lợi.',
      'Hợp tác trên cơ sở kinh doanh đáng tin cậy, bảo đảm chất lượng hàng hóa và tiến độ thanh quyết toán.',
      'Hỗ trợ lẫn nhau để cùng nâng cao chất lượng kinh doanh, tôn vinh và gìn giữ đạo đức kinh doanh.',
    ],
  },
  {
    target: 'VỚI CỘNG ĐỒNG',
    icon: 'HeartHandshake',
    bullets: [
      'Hoàn thành đầy đủ trách nhiệm xã hội và nghiêm chỉnh chấp hành pháp luật.',
      'Bảo vệ môi trường trong quá trình sản xuất và thi công tại các công trường.',
      'Tích cực tham gia các hoạt động xã hội, góp phần vào sự phát triển phồn vinh của đất nước.',
    ],
  },
];

export const SERVICES_DATA = [
  {
    id: 'ceiling',
    code: '01',
    title: 'THI CÔNG TRẦN',
    subtitle: 'Trần thạch cao ISO & Trần kim loại',
    desc: 'Trần thạch cao tiêu chuẩn ISO được sản xuất trên dây chuyền công nghệ cao, trần kim loại khu vực trong nhà và sảnh khách sạn 5 sao với độ chính xác và tính thẩm mỹ tuyệt đối.',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    features: [
      'Trần thạch cao chìm, trần giật cấp nghệ thuật',
      'Trần thạch cao thả, trần tiêu âm phòng họp',
      'Trần kim loại (nhôm caro, clip-in, lay-in) cao cấp',
      'Đạt tiêu chuẩn chất lượng ISO & độ bền cơ học cao',
    ],
  },
  {
    id: 'partition',
    code: '02',
    title: 'THI CÔNG VÁCH',
    subtitle: 'Vách ngăn thạch cao & Vách kỹ thuật',
    desc: 'Thi công hệ thống vách thạch cao ngăn phòng, vách cách âm, vách chống cháy cho các dự án khách sạn, trung tâm thương mại, showroom ô tô và căn hộ cao cấp.',
    image: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f3?auto=format&fit=crop&w=800&q=80',
    features: [
      'Vách thạch cao 1 mặt, 2 mặt cách âm tiêu chuẩn',
      'Vách chống cháy chuyên dụng cho công trình cao tầng',
      'Vách thạch cao chống ẩm cho khu vực vệ sinh & bếp',
      'Khung xương chịu lực chính hãng, lắp đặt chuẩn xác',
    ],
  },
  {
    id: 'painting',
    code: '03',
    title: 'SƠN BẢ HOÀN THIỆN',
    subtitle: 'Sơn bả trong & ngoài nhà - Phào GFRC',
    desc: 'Cung cấp vật tư và thi công sơn bả mặt ngoài, bả sơn trong nhà, lắp dựng hoàn thiện phào chỉ GFRC (bê tông sợi thủy tinh) sắc nét, chống thấm, bền màu vượt trội.',
    image: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=800&q=80',
    features: [
      'Sơn bả tường và trần trong nhà thẩm mỹ cao',
      'Thi công bả sơn mặt ngoài chống chịu thời tiết khắc nghiệt',
      'Sản xuất & lắp đặt phào chỉ GFRC nghệ thuật kiến trúc',
      'Ứng dụng máy phun sơn và máy mài bả công suất lớn',
    ],
  },
  {
    id: 'fitout',
    code: '04',
    title: 'NỘI THẤT & HOÀN THIỆN XÂY DỰNG',
    subtitle: 'Fit-out trọn gói: Decorate, Design, Furniture, M&E',
    desc: 'Dịch vụ tổng hợp khép kín từ thiết kế, trang trí nội thất quốc tế, sản xuất đồ gỗ Furniture cao cấp đến lắp đặt hệ thống điện - cơ điện M&E cho showroom, văn phòng, khách sạn.',
    image: 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?auto=format&fit=crop&w=800&q=80',
    features: [
      'DECORATE: Trang trí nội thất văn phòng, khách sạn, nhà ở chuẩn quốc tế',
      'DESIGN: Thiết kế với phần mềm 3D/BIM ứng dụng tiên tiến nhất thế giới',
      'FURNITURE: Sản xuất đồ gỗ MDF, MFC, Inox, da, ván lạng cao cấp',
      'M&E & SERVICE: Cung cấp & thi công thiết bị điện, chiếu sáng, bảo hành dài hạn',
    ],
  },
];

export const PERSONNEL_DATA: PersonnelItem[] = [
  {
    role: 'Kiến trúc sư & Kỹ sư thiết kế',
    count: 4,
    desc: 'Chuyên trách tư vấn giải pháp, dựng phối cảnh 3D và triển khai bản vẽ kỹ thuật chi tiết.',
  },
  {
    role: 'Kỹ sư nhà máy & Công trường',
    count: 8,
    desc: 'Giám sát kỹ thuật trực tiếp, chỉ huy thi công, quản lý an toàn và kiểm soát tiến độ tại công trường.',
  },
  {
    role: 'Cử nhân kinh tế & Đấu thầu',
    count: 3,
    desc: 'Lập dự toán, quản lý chi phí, lập hồ sơ đấu thầu và theo dõi hợp đồng kinh tế dự án.',
  },
  {
    role: 'Kế toán & Hành chính văn phòng',
    count: 3,
    desc: 'Quản lý tài chính, nhân sự, chứng từ thanh quyết toán và pháp lý doanh nghiệp.',
  },
  {
    role: 'Công nhân kỹ thuật tại xưởng & công trình',
    count: 36,
    desc: 'Đội ngũ thợ lành nghề chuyên sâu về trần thạch cao, cơ khí, sơn bả và mộc nội thất.',
  },
  {
    role: 'Lao động thời vụ theo dự án',
    count: 200,
    desc: 'Lực lượng nhân công cơ động sẵn sàng huy động từ 50 - 200 nhân sự cho các dự án quy mô lớn.',
  },
];

export const EQUIPMENT_DATA: EquipmentItem[] = [
  {
    id: 'drill',
    name: 'Máy khoan bê tông chuyên dụng',
    quantity: 70,
    unit: 'Chiếc',
    description: 'Khoan cấy bu lông, nở rút và lắp đặt hệ khung chịu lực trên kết cấu bê tông.',
  },
  {
    id: 'screwdriver',
    name: 'Máy bắn vít thạch cao & kim loại',
    quantity: 120,
    unit: 'Chiếc',
    description: 'Thi công bắn tấm trần thạch cao, vách ngăn và liên kết khung nhôm nhanh chóng.',
  },
  {
    id: 'laser',
    name: 'Máy Laser định vị độ cao & góc chuẩn',
    quantity: 65,
    unit: 'Chiếc',
    description: 'Định vị cao độ trần, gióng thẳng tim vách với độ sai số cực nhỏ dưới 1mm.',
  },
  {
    id: 'welder',
    name: 'Máy hàn công nghiệp & hàn điện',
    quantity: 15,
    unit: 'Chiếc',
    description: 'Gia công lắp dựng kết cấu thép treo, khung xương kim loại và phụ kiện chịu tải.',
  },
  {
    id: 'cutter',
    name: 'Máy cắt bàn & Máy cắt cầm tay',
    quantity: 40,
    unit: 'Chiếc',
    description: 'Cắt thanh xương kim loại, tấm thạch cao, gỗ nội thất theo kích thước thiết kế.',
  },
];

export const PROJECTS_DATA: Project[] = [
  {
    id: 'the-watson-hotel',
    title: 'Dự án The Watson Hotel Hạ Long',
    location: 'Bãi Cháy, TP. Hạ Long, Tỉnh Quảng Ninh',
    scope: 'Thi công hệ thống Trần thạch cao, Vách ngăn & Sơn bả hoàn thiện các tầng khách sạn',
    category: 'hotel',
    categoryLabel: 'Khách sạn & Nghỉ dưỡng',
    region: 'north',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80',
    pageInPdf: 16,
    year: '2023 - 2024',
    description: 'Khách sạn nghỉ dưỡng cao cấp đạt tiêu chuẩn quốc tế tại bờ vịnh Hạ Long.',
  },
  {
    id: 'the-yacht-hotel',
    title: 'Dự án The Yacht Hotel',
    location: 'Bãi Cháy, TP. Hạ Long, Tỉnh Quảng Ninh',
    scope: 'Thi công trần trang trí sảnh, phòng nghỉ và hoàn thiện sơn bả cao cấp',
    category: 'hotel',
    categoryLabel: 'Khách sạn & Nghỉ dưỡng',
    region: 'north',
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
    pageInPdf: 17,
    year: '2023',
    description: 'Khách sạn boutique sang trọng kết hợp phong cách du thuyền hiện đại.',
  },
  {
    id: 'jinyu-tay-ninh',
    title: 'Dự án Nhà xưởng Tập đoàn JINYU Tây Ninh',
    client: 'CTY TNHH COGNIPLUS INTERIORS',
    location: 'Lô 9 KCN Phước Đông, Trảng Bàng, Tây Ninh',
    scope: 'Hạng mục FIT - OUT (Showroom & Multifunction Area)',
    category: 'industrial',
    categoryLabel: 'Nhà xưởng & Công nghiệp',
    region: 'south',
    image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=800&q=80',
    pageInPdf: 18,
    year: '2022 - 2023',
    description: 'Tổ hợp nhà máy sản xuất lốp xe công nghệ cao Jinyu Tire tại KCN Phước Đông.',
  },
  {
    id: 'vinfast-showrooms',
    title: 'Dự án Chuỗi Showroom VINFAST QS 3 Phía Nam',
    client: 'TẬP ĐOÀN VINGROUP / VINFAST',
    location: 'Các tỉnh thành khu vực Phía Nam',
    scope: 'Thi công trần thạch cao tiêu âm, trần phẳng sơn bả sắc nét & hoàn thiện nội thất chuẩn nhận diện VinFast quốc tế',
    category: 'commercial',
    categoryLabel: 'Thương mại & Showroom',
    region: 'south',
    image: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=800&q=80',
    pageInPdf: 19,
    year: '2022 - 2024',
    description: 'Hệ thống showroom ô tô điện và trung tâm dịch vụ khách hàng VinFast chuẩn quốc tế. Hạng mục thi công trần thạch cao cho tập đoàn lớn đòi hỏi tiến độ nhanh, bề mặt siêu phẳng mịn và kiểm soát ánh sáng khắt khe.',
  },
  {
    id: 'vinhomes-grand-park',
    title: 'Dự án Đại đô thị Vinhomes Grand Park',
    client: 'TẬP ĐOÀN VINGROUP',
    location: 'Đường Phước Thiện, Long Mỹ, TP. Thủ Đức (Q9), TP. Hồ Chí Minh',
    scope: 'Thi công hệ thống trần thạch cao chìm giật cấp, vách ngăn chống cháy căn hộ & khu tiện ích công cộng',
    category: 'residential',
    categoryLabel: 'Đô thị & Chung cư cao tầng',
    region: 'south',
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
    pageInPdf: 20,
    year: '2021 - 2023',
    description: 'Đại đô thị thông minh đẳng cấp quốc tế của Tập đoàn VinGroup quy mô hàng chục ngàn căn hộ. Trần Gia trực tiếp thi công trần vách thạch cao khối căn hộ và sảnh đón tiêu chuẩn cao.',
  },
  {
    id: 'nam-hoi-an-5star',
    title: 'Dự án Khách sạn 5 sao Nam Hội An',
    client: 'TẬP ĐOÀN VINGROUP / ĐỐI TÁC LIÊN DANH',
    location: 'Nam Hội An, Tỉnh Quảng Nam',
    scope: 'Thi công hệ trần vách thạch cao cách âm, trang trí sảnh hội nghị và biệt thự biển chuẩn 5 sao',
    category: 'hotel',
    categoryLabel: 'Khách sạn & Nghỉ dưỡng',
    region: 'central',
    image: 'https://images.unsplash.com/photo-1571896349842-33c89424de2d?auto=format&fit=crop&w=800&q=80',
    pageInPdf: 21,
    year: '2021 - 2022',
    description: 'Quần thể khách sạn nghỉ dưỡng 5 sao sang trọng ven biển miền Trung thuộc hệ sinh thái VinGroup. Đòi hỏi kỹ thuật thi công trần thạch cao giật cấp nghệ thuật kết hợp cách âm tiêu âm cao cấp.',
  },
  {
    id: 'charm-group-dian',
    title: 'Dự án Tòa nhà ở cao tầng Charm Group',
    client: 'TẬP ĐOÀN CHARM GROUP',
    location: 'Ngã tư 550, Dĩ An, Tỉnh Bình Dương',
    scope: 'Thi công trần thạch cao, vách ngăn chống cháy các tầng căn hộ và shophouse thương mại',
    category: 'residential',
    categoryLabel: 'Đô thị & Chung cư cao tầng',
    region: 'south',
    image: 'https://images.unsplash.com/photo-1515263487990-61b07816b324?auto=format&fit=crop&w=800&q=80',
    pageInPdf: 22,
    year: '2022 - 2023',
    description: 'Tổ hợp căn hộ cao cấp biểu tượng mới tại trung tâm Dĩ An, Bình Dương. Trần Gia đảm nhận thi công trần thạch cao và vách ngăn kỹ thuật đạt tiêu chuẩn kiểm định PCCC.',
  },
  {
    id: 'vincom-dian',
    title: 'Dự án Trung tâm thương mại Vincom Dĩ An Bình Dương',
    client: 'TẬP ĐOÀN VINGROUP / VINCOM RETAIL',
    location: 'Dĩ An, Tỉnh Bình Dương',
    scope: 'Thi công trần vách thạch cao sảnh thương mại, cụm rạp chiếu phim cách âm và hành lang kỹ thuật',
    category: 'commercial',
    categoryLabel: 'Thương mại & Showroom',
    region: 'south',
    image: 'https://images.unsplash.com/photo-1567449303078-57ad995bd301?auto=format&fit=crop&w=800&q=80',
    pageInPdf: 23,
    year: '2021',
    description: 'Trung tâm mua sắm, ẩm thực và giải trí hiện đại bậc nhất khu vực của VinGroup. Thi công trần vách thạch cao giật cấp không gian lớn chịu rung động và tiêu âm chuyên sâu.',
  },
  {
    id: 'ruby-ha-long',
    title: 'Dự án Khu Chung cư, Khách sạn, TM & DV Ruby Hạ Long',
    location: 'TP. Hạ Long, Tỉnh Quảng Ninh',
    scope: 'Thi công trần thạch cao và sơn bả hoàn thiện các khối tháp',
    category: 'residential',
    categoryLabel: 'Đô thị & Chung cư cao tầng',
    region: 'north',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
    pageInPdf: 26,
    year: '2022',
    description: 'Khu phức hợp căn hộ, khách sạn và dịch vụ thương mại nhìn ra vịnh Cửa Lục.',
  },
  {
    id: 'masteri-hung-yen',
    title: 'Dự án Masteri Hưng Yên',
    client: 'MASTERISE HOMES',
    location: 'Khu đô thị Ocean Park 2/3, Văn Giang, Hưng Yên',
    scope: 'Thi công trần vách thạch cao căn hộ mẫu và sảnh đón tiêu chuẩn Masterise',
    category: 'residential',
    categoryLabel: 'Đô thị & Chung cư cao tầng',
    region: 'north',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=800&q=80',
    pageInPdf: 27,
    year: '2023 - 2024',
    description: 'Phân khu căn hộ hạng sang chuẩn quốc tế của Masterise Homes.',
  },
  {
    id: 'nam-ngan-thanh-hoa',
    title: 'Dự án KĐT Phía Đông Đại Lộ Bắc Nam Nam Ngạn',
    client: 'CÔNG TY CỔ PHẦN TỔNG CÔNG TY MBLAND',
    location: 'Phường Nam Ngạn, TP. Thanh Hóa, Tỉnh Thanh Hóa',
    scope: 'Hạng mục: Thi công bả sơn mặt ngoài, lắp dựng phào chỉ GFRC nghệ thuật',
    category: 'residential',
    categoryLabel: 'Đô thị & Chung cư cao tầng',
    region: 'central',
    image: 'https://images.unsplash.com/photo-1577495508048-b635879837f1?auto=format&fit=crop&w=800&q=80',
    pageInPdf: 28,
    year: '2023',
    description: 'Khu đô thị hiện đại với kiến trúc tân cổ điển đòi hỏi tay nghề thi công phào GFRC tinh xảo.',
  },
  {
    id: 'tttm-hai-duong',
    title: 'Dự án Trung tâm thương mại Phức hợp Hải Dương',
    client: 'CÔNG TY TNHH TẬP ĐOÀN XÂY DỰNG DELTA',
    location: 'Số 2 Phố Thống Nhất, P. Lê Thanh Nghị, TP. Hải Dương',
    scope: 'Hạng mục: Cung cấp vật tư và thi công sơn bả ngoài nhà',
    category: 'commercial',
    categoryLabel: 'Thương mại & Showroom',
    region: 'north',
    image: 'https://images.unsplash.com/photo-1555636222-cae831e670b3?auto=format&fit=crop&w=800&q=80',
    pageInPdf: 29,
    year: '2023',
    description: 'Tòa nhà thương mại phức hợp điểm nhấn trung tâm thành phố Hải Dương.',
  },
  {
    id: 'sentosa-sky-park',
    title: 'Dự án Sentosa Sky Park Hải Phòng',
    client: 'CÔNG TY CỔ PHẦN XÂY DỰNG VÀ ỨNG DỤNG CÔNG NGHỆ DELTA-V',
    location: 'Giao lộ Bùi Viện - Võ Nguyên Giáp, Lê Chân, TP. Hải Phòng',
    scope: 'Hạng mục: Cung cấp vật tư, thi công trần, vách thạch cao, sơn bả trần thạch cao',
    category: 'residential',
    categoryLabel: 'Đô thị & Chung cư cao tầng',
    region: 'north',
    image: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=800&q=80',
    pageInPdf: 30,
    year: '2023 - 2024',
    description: 'Chung cư cao cấp phong cách Singapore tại trung tâm giao thương TP. Hải Phòng.',
  },
  {
    id: 'dong-gia-5star-hotel',
    title: 'Dự án Khách sạn 5 sao Đồng Gia',
    client: 'CHI NHÁNH CÔNG TRÌNH VIETTEL HÀ NỘI - TỔNG CÔNG TY CỔ PHẦN CÔNG TRÌNH VIETTEL',
    location: 'Phường Bãi Cháy, TP. Hạ Long, Tỉnh Quảng Ninh',
    scope: 'Hạng mục: Thi công trần kim loại khu vực trong nhà',
    category: 'hotel',
    categoryLabel: 'Khách sạn & Nghỉ dưỡng',
    region: 'north',
    image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
    pageInPdf: 31,
    year: '2024',
    description: 'Khách sạn 5 sao cao cấp ứng dụng trần kim loại kỹ thuật cao chống ẩm mặn vùng biển.',
  },
  {
    id: 'at-sky-garden',
    title: 'Dự án Chung cư cao cấp A&T Sky Garden',
    client: 'CÔNG TY CỔ PHẦN XÂY DỰNG CDC',
    location: 'Số 54C, Cách Mạng Tháng 8, Phường Lái Thiêu, TP. Thuận An / TP.HCM',
    scope: 'Hạng mục: Thi công hạng mục trần thạch cao khối căn hộ',
    category: 'residential',
    categoryLabel: 'Đô thị & Chung cư cao tầng',
    region: 'south',
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
    pageInPdf: 32,
    year: '2024',
    description: 'Khu chung cư cao cấp bên sông với thiết kế xanh và trần thạch cao tinh tế.',
  },
];

export const PARTNERS_DATA: Partner[] = [
  // 1. Tập đoàn & Chủ đầu tư
  {
    id: 'vingroup',
    name: 'TẬP ĐOÀN VINGROUP',
    role: 'Tập đoàn BĐS, Công nghiệp & Dịch vụ số 1 Việt Nam',
    category: 'developer',
    badge: 'Chủ đầu tư Chiến lược',
    brandColor: '#B91C1C',
    thumbnail: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&w=600&q=80',
    logo: 'https://thumb.wikimedia.org/wikipedia/vi/thumb/9/98/Vingroup_logo.svg/1280px-Vingroup_logo.svg.png?utm_source=vi.wikipedia.org&utm_campaign=index&utm_content=thumbnail',
    projects: ['Vinhomes Grand Park', 'Chuỗi Showroom VinFast QS 3', 'Vincom Dĩ An', 'Khách sạn 5 sao Nam Hội An'],
    description: 'Trần Gia vinh dự được lựa chọn thi công trần vách thạch cao và hoàn thiện cho nhiều dự án trọng điểm trong hệ sinh thái VinGroup.',
  },
  {
    id: 'masterise',
    name: 'MASTERISE HOMES',
    role: 'Nhà phát triển BĐS Hàng hiệu & Hạng sang Quốc tế',
    category: 'developer',
    badge: 'Chủ đầu tư Hạng sang',
    brandColor: '#B45309',
    logo: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=300&q=80',
    projects: ['Masteri Hưng Yên (Ocean Park 2/3)'],
    description: 'Đối tác thi công trần vách thạch cao sảnh đón và căn hộ mẫu với tiêu chuẩn hoàn thiện khắt khe chuẩn Masterise quốc tế.',
  },
  {
    id: 'mbland',
    name: 'MBLAND HOLDINGS',
    role: 'Tổng công ty Cổ phần MBLAND (MB Group)',
    category: 'developer',
    badge: 'Chủ đầu tư Đô thị',
    brandColor: '#1D4ED8',
    logo: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=300&q=80',
    projects: ['KĐT Nam Ngạn Đại Lộ Bắc Nam Thanh Hóa'],
    description: 'Chủ đầu tư đại dự án KĐT Nam Ngạn, Trần Gia đảm nhiệm hạng mục bả sơn mặt ngoài và lắp dựng phào chỉ nghệ thuật GFRC.',
  },
  {
    id: 'charm-group',
    name: 'CHARM GROUP',
    role: 'Tập đoàn Đầu tư & Phát triển BĐS Nghỉ dưỡng',
    category: 'developer',
    badge: 'Chủ đầu tư',
    brandColor: '#047857',
    logo: 'https://images.unsplash.com/photo-1515263487990-61b07816b324?auto=format&fit=crop&w=300&q=80',
    projects: ['Tòa nhà ở cao tầng Charm Group Dĩ An'],
    description: 'Chủ đầu tư tổ hợp căn hộ biểu tượng tại Bình Dương với hệ thống trần thạch cao và vách ngăn chống cháy chất lượng cao.',
  },

  // 2. Tổng thầu Xây dựng Hàng đầu
  {
    id: 'delta-group',
    name: 'TẬP ĐOÀN XÂY DỰNG DELTA',
    role: 'Tổng thầu Xây dựng Dân dụng & Công nghiệp Top đầu Việt Nam',
    category: 'contractor',
    badge: 'Tổng thầu Chiến lược',
    brandColor: '#0369A1',
    logo: 'https://deltagroup.vn/wp-content/uploads/2020/06/tr4-1.png',
    projects: ['TTTM Phức hợp Hải Dương', 'Sentosa Sky Park Hải Phòng'],
    description: 'Đồng hành cùng Tổng thầu DELTA qua hàng loạt gói thầu thi công trần thạch cao, sơn bả hoàn thiện các tòa cao ốc quy mô lớn.',
  },
  {
    id: 'viettel-construction',
    name: 'VIETTEL CONSTRUCTION',
    role: 'Tổng công ty Cổ phần Công trình Viettel (Viettel Group)',
    category: 'contractor',
    badge: 'Tổng thầu Quốc gia',
    brandColor: '#DC2626',
    logo: 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f3?auto=format&fit=crop&w=300&q=80',
    projects: ['Khách sạn 5 sao Đồng Gia Hạ Long'],
    description: 'Đối tác chiến lược cùng Tổng công ty Công trình Viettel thi công hệ trần kim loại kỹ thuật cao cho khách sạn 5 sao tại Hạ Long.',
  },
  {
    id: 'cdc-construction',
    name: 'CDC CONSTRUCTION',
    role: 'Công ty Cổ phần Xây dựng CDC',
    category: 'contractor',
    badge: 'Tổng thầu Uy tín',
    brandColor: '#4338CA',
    logo: 'https://images.unsplash.com/photo-1503387762-592deb58ef4e?auto=format&fit=crop&w=300&q=80',
    projects: ['Chung cư cao cấp A&T Sky Garden'],
    description: 'Tổng thầu xây dựng dự án A&T Sky Garden, Trần Gia trực tiếp đảm nhận toàn bộ gói thầu trần thạch cao khối căn hộ cao cấp.',
  },
  {
    id: 'cogniplus',
    name: 'COGNIPLUS INTERIORS',
    role: 'Tổng thầu Nội thất & Fit-out Công nghiệp Quốc tế',
    category: 'contractor',
    badge: 'Tổng thầu Fit-out',
    brandColor: '#D97706',
    logo: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=300&q=80',
    projects: ['Fit-out Nhà xưởng Jinyu Tây Ninh'],
    description: 'Hợp tác trong các gói thầu Fit-out, vách thạch cao ngăn phòng sạch và trần tiêu âm cho các dự án nhà máy công nghiệp FDI.',
  },

  // 3. Nhà sản xuất & Cung cấp vật tư chính hãng
  {
    id: 'vinhtuong-gyproc',
    name: 'VĨNH TƯỜNG - GYPROC (SAINT-GOBAIN)',
    role: 'Tập đoàn Giải pháp Trần & Vách Thạch cao Hàng đầu',
    category: 'manufacturer',
    badge: 'Nhà sản xuất Chính hãng',
    brandColor: '#0284C7',
    logo: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&w=300&q=80',
    projects: ['Toàn bộ các dự án trọng điểm toàn quốc'],
    description: 'Đối tác cung ứng vật tư khung xương, tấm thạch cao tiêu chuẩn & chống cháy với đầy đủ chứng chỉ chất lượng CO/CQ.',
  },
  {
    id: 'knauf-vietnam',
    name: 'KNAUF VIỆT NAM',
    role: 'Tập đoàn Vật liệu Thạch cao Tiêu chuẩn Đức (CHLB Đức)',
    category: 'manufacturer',
    badge: 'Nhà sản xuất Quốc tế',
    brandColor: '#0D9488',
    logo: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=300&q=80',
    projects: ['Dự án tiêu chuẩn tiêu âm & chống ẩm đặc biệt'],
    description: 'Đối tác cung cấp hệ thống tấm thạch cao kỹ thuật cao, tấm tiêu âm Danoline và giải pháp vách ngăn chịu ẩm cao cấp.',
  },
  {
    id: 'jotun-dulux',
    name: 'JOTUN & DULUX (AKZONOBEL)',
    role: 'Thương hiệu Sơn & Bột bả Kiến trúc Cao cấp Thế giới',
    category: 'manufacturer',
    badge: 'Vật tư Sơn bả',
    brandColor: '#E11D48',
    logo: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?auto=format&fit=crop&w=300&q=80',
    projects: ['Các khối tháp căn hộ & TTTM'],
    description: 'Đối tác cung cấp bột bả và sơn hoàn thiện bề mặt trần vách thạch cao cao cấp cho các công trình cấp tập đoàn.',
  },
];
